CREATE TABLE CATEGORIE (
  ID_CAT INTEGER                NOT NULL AUTO_INCREMENT,
  NOM_CAT varchar(40)           NOT NULL,
  DESCRIPTION_CAT varchar(40)   NOT NULL,
  PRIMARY KEY (ID_CAT)
  ) ;

CREATE TABLE PRODUIT (
  ID_PRODUIT INTEGER            NOT NULL AUTO_INCREMENT,
  NOM_PRODUIT varchar(40)       NOT NULL,
  PRIX_PRODUIT varchar(40)      NOT NULL,
  DATE_CREATION datetime        NOT NULL,
  ID_CAT INTEGER                    NULL,
  PRIMARY KEY (ID_PRODUIT),
  CONSTRAINT FK_PRODUIT_CATEGORIE FOREIGN KEY (ID_CAT) REFERENCES CATEGORIE (ID_CAT)
  ) ;